### PR TITLE
 User Form - JavaScript Validation & Calculator

### PR DESCRIPTION
**Pull request by vasilena14**
This change contains a simple HTML form with added CSS styling and a JavaScript client-side validation of the input.

### CODE REVIEW

**Comment by vasilena14** [comment]
Added new files that contain a simple HTML page with a calculator, CSS and JavaScript files for its styling and functionality.

**Comment by mgenov** [comment]
This branch need to be fixed as it's not coming from the master of upstream.

**Comment by mgenov** [comment]
It still cannot be merged. 

This is how the history of upstream looks like:
screen shot 2018-06-27 at 12 29 02

This is the history of vasilena14:master

screen shot 2018-06-27 at 12 29 12

e.g as you can see both history lines are difference and this is why this PR cannot be merged into the upstream. 

As steps you can perform the following to make it working: 

Adding Upstream to the repository (if not already exists)
```
git remote add upstream git@github.com:clouway-incubator/vasilena_vasileva_html_css.git
```


Copy existing sources into temporary folder
```
mkdir -p $HOME/temp/htmltask
cp -fr * $HOME/temp/htmltask/
```

Make a future branch from the master of upstream
```
git fetch upstream
git checkout -b html_tasks upstream/master
```

Copy source files & commit 
```
cp -fr $HOME/temp/htmltask/* .
git add .
git commit -a 
```

Push Branch to origin
```
git push origin html_tasks
```

**Comment by vasilena14** [comment]
I understand it now. Thanks!

**Pull request merged**
